import dns from 'dns';
dns.setServers(['8.8.8.8', '8.8.4.4']);

import mongoose from 'mongoose';
import dotenv from 'dotenv';
import SiteSettings from './models/SiteSettings';
import HarvestCalendar from './models/HarvestCalendar';

dotenv.config();

// ── Hasat Takvimi Verileri ──
// Turkiye'nin ana tarim urunleri — TUIK uretim istatistikleri + bolgesel iklim verilerine gore
const harvestItems = [
  // ═══════════════════════════════════════════════════════════
  // SEBZELER (Meyvemsi · Yaprak · Kok · Sogansi · Baklagiller taze)
  // ═══════════════════════════════════════════════════════════
  { product: 'Domates', productEn: 'Tomato', category: 'sebze', plantMonths: [3, 4, 5], harvestMonths: [7, 8, 9, 10], regions: ['Akdeniz', 'Ege', 'Marmara'], description: 'Türkiye\'nin en çok üretilen sebzesi. Sıcak iklim sever, don riskinden korunmalı.', tips: ['Fide dikimi gece sıcaklığı 10°C üzeri olduğunda yapılmalı', 'Düzenli sulama ve destekleme gerekli', 'Yaprak hastalıklarına karşı koruyucu ilaçlama önerilir'] },
  { product: 'Biber', productEn: 'Pepper', category: 'sebze', plantMonths: [3, 4, 5], harvestMonths: [7, 8, 9, 10], regions: ['Akdeniz', 'Ege', 'Güneydoğu Anadolu'], description: 'Çarliston, kapya, dolmalık, sivri ve acı çeşitleri. Sera ve açıkta yetiştirilebilir.', tips: ['Toprağın 15°C üzerine çıkmasını bekleyin', 'Meyve tutumu döneminde kalsiyum takviyesi yapın', 'Aşırı sulamadan kaçının'] },
  { product: 'Patlıcan', productEn: 'Eggplant', category: 'sebze', plantMonths: [3, 4, 5], harvestMonths: [6, 7, 8, 9, 10], regions: ['Akdeniz', 'Ege', 'Marmara'], description: 'Sıcak iklim bitkisi, dona hassas. Verimli toprak ve düzenli sulama ister.', tips: ['Don riski geçtikten sonra dikin', 'Solgunluk hastalığına dayanıklı çeşit tercih edin', 'Budama ile verimi artırın'] },
  { product: 'Salatalık', productEn: 'Cucumber', category: 'sebze', plantMonths: [4, 5], harvestMonths: [6, 7, 8, 9], regions: ['Akdeniz', 'Ege', 'Marmara', 'Karadeniz'], description: 'Hızlı büyüyen, bol su isteyen sebze. Sera ve tarlada yetişir.', tips: ['İpe sarma sistemi ile dikey yetiştirme verimi artırır', 'Külleme hastalığına dikkat', 'Günde 2-3 kez hasat kontrolü yapın'] },
  { product: 'Kabak', productEn: 'Zucchini', category: 'sebze', plantMonths: [4, 5], harvestMonths: [6, 7, 8, 9], regions: ['Akdeniz', 'Ege', 'Marmara'], description: 'Kolay yetiştirilen, verimli sebze. Geniş alan ister.', tips: ['Tozlaşma için arı popülasyonunu koruyun', 'Küçükken hasat daha lezzetli olur', 'Küllemeye dikkat edin'] },
  { product: 'Bal Kabağı', productEn: 'Pumpkin', category: 'sebze', plantMonths: [4, 5], harvestMonths: [9, 10, 11], regions: ['İç Anadolu', 'Ege', 'Marmara'], description: 'Uzun raf ömürlü kış sebzesi. Çekirdekleri yağlı tohum olarak da değerlendirilir.', tips: ['Toprağı iyi hazırlayın, bol organik madde ekleyin', 'Tam olgunlaştığında sapı 5-10 cm bırakarak kesin', 'Serin kuru yerde 6 aya kadar saklanır'] },
  { product: 'Kavun', productEn: 'Melon', category: 'sebze', plantMonths: [4, 5], harvestMonths: [7, 8, 9], regions: ['İç Anadolu', 'Ege', 'Akdeniz'], description: 'Diyarbakır, Kırkağaç, Ankara çeşitleri ile ünlüdür. Sıcak ve kurak sever.', tips: ['Malçlama ile meyve kalitesini artırın', 'Şeker oranı için hasat öncesi sulamayı kesin', 'Koku ve çatlak dökümü ile olgunluk anlaşılır'] },
  { product: 'Karpuz', productEn: 'Watermelon', category: 'sebze', plantMonths: [4, 5], harvestMonths: [6, 7, 8], regions: ['Güneydoğu Anadolu', 'Akdeniz', 'İç Anadolu'], description: 'Diyarbakır ve Adana öne çıkıyor. Yüksek sıcaklık ve bol su ister.', tips: ['Ekim öncesi toprağa bol gübre verin', 'Sırıklama ile meyveyi topraktan yukarı alın', 'Vuruş sesi ve sap kuruması olgunluk göstergesidir'] },
  { product: 'Soğan', productEn: 'Onion', category: 'sebze', plantMonths: [2, 3, 10, 11], harvestMonths: [6, 7, 8], regions: ['İç Anadolu', 'Güneydoğu Anadolu', 'Akdeniz'], description: 'Her mutfağın vazgeçilmezi. Kuru iklimde daha iyi sonuç verir.', tips: ['Arpacık soğan Şubat-Mart\'ta dikilir', 'Yapraklar devrildiğinde hasat zamanı gelmiştir', 'Hasattan 2 hafta önce sulamayı kesin'] },
  { product: 'Taze Soğan', productEn: 'Spring Onion', category: 'sebze', plantMonths: [2, 3, 9, 10], harvestMonths: [4, 5, 6, 11, 12], regions: ['Marmara', 'Ege', 'Akdeniz'], description: 'Sürekli ekim ile yıl boyu hasat alınabilir. Yumuşak toprakta daha iyi büyür.', tips: ['Her 2-3 haftada bir tekrar ekim yapın', 'Sürekli nemli toprak ister', 'Yeşil kısım 25-30 cm olunca hasat edin'] },
  { product: 'Sarımsak', productEn: 'Garlic', category: 'sebze', plantMonths: [10, 11], harvestMonths: [6, 7], regions: ['Kastamonu', 'İç Anadolu', 'Ege'], description: 'Kastamonu Taşköprü sarımsağı coğrafi işaretli ürün. Kış ekimi ile en iyi sonuç alınır.', tips: ['Soğuklamaya ihtiyaç duyar, erken ekim kritik', 'Yaprakların %70\'i sarardığında söküm yapın', 'Sökümden sonra 2 hafta gölgede kurutun'] },
  { product: 'Patates', productEn: 'Potato', category: 'sebze', plantMonths: [3, 4], harvestMonths: [7, 8, 9], regions: ['İç Anadolu', 'Karadeniz', 'Doğu Anadolu'], description: 'Türkiye\'nin temel gıda ürünlerinden. Niğde-Nevşehir üretim merkezi.', tips: ['Sertifikalı tohumluk kullanın', 'Patates böceğine karşı erken müdahale edin', 'Yumru yeşillenmemesi için boğaz doldurma yapın'] },
  { product: 'Havuç', productEn: 'Carrot', category: 'sebze', plantMonths: [3, 4, 7, 8], harvestMonths: [6, 7, 10, 11, 12], regions: ['Ankara (Beypazarı)', 'İç Anadolu', 'Marmara'], description: 'Beypazarı havucu Türkiye üretiminin büyük kısmını karşılar. Gevşek, kumlu toprak ister.', tips: ['Tohum ekim derinliği 1-2 cm\'yi geçmesin', 'Seyreltme yapmayı ihmal etmeyin', 'Havuç sineği için yan ekim (soğan) kullanın'] },
  { product: 'Pancar', productEn: 'Beetroot', category: 'sebze', plantMonths: [3, 4, 8], harvestMonths: [6, 7, 10, 11], regions: ['İç Anadolu', 'Marmara'], description: 'Kök pancarı sofralık, şalgam suyunda ve turşuda kullanılır.', tips: ['Ekim öncesi tohumu 4-6 saat suda ıslatın', 'Seyreltme ile iri kök elde edin', 'Yapraklar da salata olarak tüketilebilir'] },
  { product: 'Turp', productEn: 'Radish', category: 'sebze', plantMonths: [3, 4, 8, 9, 10], harvestMonths: [5, 6, 10, 11, 12], regions: ['Marmara', 'Ege', 'Akdeniz'], description: 'Kırmızı, beyaz ve siyah çeşitleri. Hızlı büyür, 30-60 gün içinde hasada hazır.', tips: ['Serin havalarda daha tatlı olur', 'Sürekli ekim ile 3 mevsim hasat alın', 'Çatlamasın diye düzenli sulayın'] },
  { product: 'Şalgam', productEn: 'Turnip', category: 'sebze', plantMonths: [7, 8, 9], harvestMonths: [10, 11, 12], regions: ['Akdeniz', 'İç Anadolu'], description: 'Adana şalgam suyunun ana bileşeni. Kış sebzesi, soğuğa dayanıklı.', tips: ['Yaz sonu ekim ile kış boyu hasat', 'Külleme hastalığına karşı önlem alın', 'Yapraklar yem bitkisi olarak değerlendirilir'] },
  { product: 'Pırasa', productEn: 'Leek', category: 'sebze', plantMonths: [3, 4, 8], harvestMonths: [10, 11, 12, 1, 2], regions: ['Marmara', 'İç Anadolu', 'Ege'], description: 'Soğuğa dayanıklı kış sebzesi. İnegöl pırasası coğrafi işaretli.', tips: ['Toprak boğaz doldurma ile beyaz kısmı uzatın', 'Donla beraber tatlılaşır, kış boyu hasat edilir', 'Dikim aralığı 15-20 cm olmalı'] },
  { product: 'Lahana', productEn: 'Cabbage', category: 'sebze', plantMonths: [7, 8], harvestMonths: [10, 11, 12, 1, 2], regions: ['Karadeniz', 'Marmara', 'İç Anadolu'], description: 'Beyaz, kırmızı ve kıvırcık çeşitleri. Don dayanımı yüksek.', tips: ['Küllü topraklarda kök uru hastalığına dikkat', 'Yaprak biti için biyolojik mücadele uygulayın', 'Başların sertleşmesi hasat zamanını gösterir'] },
  { product: 'Karnabahar', productEn: 'Cauliflower', category: 'sebze', plantMonths: [7, 8], harvestMonths: [10, 11, 12, 1, 2], regions: ['Marmara', 'Ege', 'Akdeniz'], description: 'Soğuk sever yaprak sebzesi. Başın beyaz kalması için yapraklarla kapatılır.', tips: ['Baş oluştuğunda iç yaprakları üstüne katlayın', 'Sürekli nem ister, kurumaya bırakmayın', 'Hafif sarımsı olmadan önce hasat edin'] },
  { product: 'Brokoli', productEn: 'Broccoli', category: 'sebze', plantMonths: [7, 8, 2], harvestMonths: [5, 6, 10, 11, 12], regions: ['Marmara', 'Ege', 'Akdeniz'], description: 'İki sezon yetiştirilebilen sağlıklı sebze. Türkiye\'de üretimi hızla artıyor.', tips: ['Ana baş hasadından sonra yan sürgünler çıkar', 'Çiçek açmadan hasat edin', 'Gece sıcaklığı 15-20°C ideal'] },
  { product: 'Ispanak', productEn: 'Spinach', category: 'sebze', plantMonths: [9, 10, 2, 3], harvestMonths: [3, 4, 5, 11, 12], regions: ['Marmara', 'Ege', 'Akdeniz'], description: 'Kışlık ve baharlık iki ekimli soğuk iklim sebzesi. Kısa sürede hasada hazır.', tips: ['25-35 cm boy alınca dipten kesin', 'Sıcakta erken çiçeklenir, sezonunda ekin', 'Topraktan iyi azot ister'] },
  { product: 'Marul', productEn: 'Lettuce', category: 'sebze', plantMonths: [2, 3, 8, 9], harvestMonths: [4, 5, 6, 10, 11], regions: ['Marmara', 'Ege', 'Akdeniz'], description: 'Göbekli (kıvırcık) ve yapraklı tipleri. Serin iklim sever.', tips: ['Yaz ortasında kaçma (çiçeklenme) olur', 'Sık ekim yapıp seyreltin', 'Sabah hasatta daha gevrek olur'] },
  { product: 'Roka', productEn: 'Arugula', category: 'sebze', plantMonths: [2, 3, 9, 10], harvestMonths: [4, 5, 10, 11, 12], regions: ['Marmara', 'Ege'], description: 'Hızlı büyüyen, keskin tatlı salata yaprağı. 30-40 gün içinde hasat.', tips: ['Her 15 günde bir tekrar ekim yapın', 'Tam olgunlaşmadan genç hasat edin', 'Toprak kurumasına bırakmayın'] },
  { product: 'Maydanoz', productEn: 'Parsley', category: 'sebze', plantMonths: [3, 4, 9, 10], harvestMonths: [5, 6, 7, 8, 9, 10, 11], regions: ['Tüm bölgeler'], description: 'Türk mutfağının vazgeçilmezi. Düz ve kıvırcık yapraklı çeşitleri.', tips: ['Tohum çimlenmesi yavaş (2-3 hafta)', 'Dipten kesim ile sürekli hasat alın', 'Kışı geçirip ikinci yıl tohum verir'] },
  { product: 'Dereotu', productEn: 'Dill', category: 'sebze', plantMonths: [3, 4, 8, 9], harvestMonths: [5, 6, 7, 10, 11], regions: ['Marmara', 'Ege', 'Akdeniz'], description: 'Kışlık taze sebzelerin ve turşuların olmazsa olmazı. Kendi kendine tohumlanır.', tips: ['Rüzgardan korunan yerde yetiştirin', 'Çiçeklenmeden önce hasat en aromatik', 'Tohumları baharat olarak da kullanılır'] },
  { product: 'Nane', productEn: 'Mint', category: 'sebze', plantMonths: [3, 4, 9, 10], harvestMonths: [5, 6, 7, 8, 9, 10], regions: ['Akdeniz', 'Ege', 'Güneydoğu Anadolu'], description: 'Çok yıllık aromatik bitki. Kurutmalık ve taze tüketime uygun.', tips: ['Hızla yayılır, sınırlandırmak gerekebilir', 'Çiçeklenmeden hemen önce kesim yapın', 'Gölgelik yerde de yetişir'] },
  { product: 'Bamya', productEn: 'Okra', category: 'sebze', plantMonths: [4, 5], harvestMonths: [6, 7, 8, 9], regions: ['İç Anadolu (Amasya)', 'Akdeniz'], description: 'Amasya bamyası küçük tipli coğrafi işaretli üründür. Sıcak sever.', tips: ['Her gün hasat edin, hızlı sertleşir', 'Hasat için eldiven kullanın (tüyleri kaşındırır)', 'Su stresine hassastır'] },
  { product: 'Enginar', productEn: 'Artichoke', category: 'sebze', plantMonths: [2, 3], harvestMonths: [3, 4, 5, 6], regions: ['Ege (Urla)', 'Akdeniz'], description: 'Urla enginarı İzmir\'in öncü ürünlerinden. Çok yıllık, 5-6 yıl verim verir.', tips: ['Ana baş ortadan hasat edilir, yan başlar sonra', 'Çok fazla organik madde ister', 'Açmadan, sıkı iken hasat edin'] },
  { product: 'Kuşkonmaz', productEn: 'Asparagus', category: 'sebze', plantMonths: [2, 3], harvestMonths: [4, 5, 6], regions: ['Akdeniz', 'Ege'], description: 'Çok yıllık sebze (10-15 yıl verim). İlk 2-3 yıl hasat yapılmaz.', tips: ['Derin, iyi drenajlı toprak ister', 'Filizler 20 cm boy alınca kesilir', 'Her yıl kış gübrelemesi yapın'] },
  { product: 'Taze Fasulye', productEn: 'Green Bean', category: 'sebze', plantMonths: [4, 5, 6], harvestMonths: [6, 7, 8, 9], regions: ['Karadeniz', 'Marmara', 'Ege'], description: 'Bodur ve sırık çeşitleri. Sürekli ekim ile uzun sezon hasat.', tips: ['Don riski bittikten sonra ekin', 'Sırık fasulye için 2 m destek gerekir', 'Kılçığı olmayan çeşitleri tercih edin'] },
  { product: 'Taze Bakla', productEn: 'Broad Bean', category: 'sebze', plantMonths: [10, 11, 2], harvestMonths: [4, 5, 6], regions: ['Akdeniz', 'Ege', 'Marmara'], description: 'Soğuğa dayanıklı kışlık-ilkbaharlık baklagil. Taze iken kabuklu yenilir.', tips: ['Ekim aralığı 20-25 cm olmalı', 'Yaprak biti için su spreyi yeterli', 'İri, sıkı baklalar tercih edin'] },
  { product: 'Bezelye (Taze)', productEn: 'Fresh Pea', category: 'sebze', plantMonths: [2, 3, 10, 11], harvestMonths: [5, 6, 11, 12], regions: ['Marmara', 'İç Anadolu', 'Ege'], description: 'Serin iklim baklagili. Sırık bezelye daha yüksek verim verir.', tips: ['İlk çiçeklenmede destekleme yapın', 'Sürekli hasat verimi artırır', 'Hasattan sonra hızla sertleşir'] },
  { product: 'Mantar', productEn: 'Cultivated Mushroom', category: 'sebze', plantMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], regions: ['Marmara', 'İç Anadolu'], description: 'Kültür mantarı yıl boyu üretim. Kontrollü ortam (nem + sıcaklık) gerektirir.', tips: ['Kompost kalitesi en kritik faktör', 'Nem %80-90, sıcaklık 18-22°C ideal', 'CO₂ seviyesi periyodik kontrol edilmeli'] },

  // ═══════════════════════════════════════════════════════════
  // MEYVELER (Yumusak · Sert cekirdekli · Narenciye · Kuruyemis · Berries)
  // ═══════════════════════════════════════════════════════════
  { product: 'Elma', productEn: 'Apple', category: 'meyve', plantMonths: [2, 3, 11, 12], harvestMonths: [8, 9, 10], regions: ['İç Anadolu', 'Doğu Anadolu', 'Karadeniz'], description: 'Isparta, Karaman ve Niğde başlıca üretim merkezleri. Starking, Golden, Granny Smith.', tips: ['Seyreltme ile meyve kalitesini artırın', 'Elma iç kurdu için feromon tuzak kullanın', 'Hasattan 2 hafta önce sulama kesin'] },
  { product: 'Armut', productEn: 'Pear', category: 'meyve', plantMonths: [2, 3, 11, 12], harvestMonths: [7, 8, 9, 10], regions: ['Marmara (Bursa)', 'İç Anadolu', 'Ege'], description: 'Deveci, Ankara, Santa Maria çeşitleri. Bursa deveci armudu dünya kalitesinde.', tips: ['Ateş yanıklığı için zamanında ilaçlama', 'Dal budaması her yıl şubat-mart\'ta', 'Hafif ham hasat ve soğukta olgunlaştırma tercih edilir'] },
  { product: 'Ayva', productEn: 'Quince', category: 'meyve', plantMonths: [2, 3, 11, 12], harvestMonths: [9, 10, 11], regions: ['Marmara', 'Ege', 'Akdeniz'], description: 'Geç hasat meyvesi. Reçel, komposto ve hoşafta kullanılır.', tips: ['Geç çiçeklendiği için don zararı az', 'Monilya hastalığına dikkat', 'Meyveler tamamen sararınca hasat edin'] },
  { product: 'Kiraz', productEn: 'Cherry', category: 'meyve', plantMonths: [12, 1, 2], harvestMonths: [5, 6, 7], regions: ['Afyon', 'Manisa', 'Isparta', 'İzmir'], description: '0900 Ziraat çeşidi dünyaca ünlü. Türkiye dünya ihracatında lider.', tips: ['Yaz budaması verimi artırır', 'Çatlama için hasat öncesi sulamaya dikkat', 'Sineğe karşı tuzak + ilaçlama kombinasyonu'] },
  { product: 'Vişne', productEn: 'Sour Cherry', category: 'meyve', plantMonths: [12, 1, 2], harvestMonths: [6, 7], regions: ['Afyon', 'İç Anadolu', 'Marmara'], description: 'Kiraza göre daha soğuğa dayanıklı. Reçel, meyve suyu ve likörde kullanılır.', tips: ['Sap ile hasat işlem kolaylığı sağlar', 'Karaleke hastalığına dikkat', 'Yaz budaması önerilir'] },
  { product: 'Şeftali', productEn: 'Peach', category: 'meyve', plantMonths: [12, 1, 2], harvestMonths: [6, 7, 8, 9], regions: ['Bursa', 'Mersin', 'İzmir', 'Manisa'], description: 'Bursa şeftalisi coğrafi işaretli. Sarı etli, beyaz etli ve düz şeftali çeşitleri.', tips: ['Her yıl budama şarttır', 'Yaprak kıvırcıklığına karşı dinlenme sonrası ilaçlama', 'Seyreltme ile iri meyve elde edilir'] },
  { product: 'Nektarin', productEn: 'Nectarine', category: 'meyve', plantMonths: [12, 1, 2], harvestMonths: [6, 7, 8], regions: ['Bursa', 'Mersin', 'Ege'], description: 'Şeftalinin tüysüz türevi. Daha yüksek şeker ve aroma içerir.', tips: ['Şeftali ile benzer bakım gerektirir', 'Meyve sineği erken müdahale ister', 'Olgunlaşma hızlı, zamanında hasat kritik'] },
  { product: 'Kayısı', productEn: 'Apricot', category: 'meyve', plantMonths: [12, 1, 2], harvestMonths: [6, 7, 8], regions: ['Malatya', 'Elazığ', 'Ege'], description: 'Malatya kayısısı dünya üretiminin yarısı. Kurutmalık ve sofralık çeşitleri.', tips: ['Don riskine çok hassas, geç çiçek çeşidi seçin', 'Seyreltme şart, dal yoğunluğu düşürülmeli', 'Kurutma için güneş ve havalandırma gerekir'] },
  { product: 'Erik', productEn: 'Plum', category: 'meyve', plantMonths: [12, 1, 2], harvestMonths: [5, 6, 7, 8], regions: ['Ege', 'Marmara', 'İç Anadolu'], description: 'Can eriği, papaz, mürdüm ve yeşil erik çeşitleri. Kısa raf ömrü.', tips: ['Can eriği nisan-mayısta erken hasat', 'Monilya hastalığına karşı sürgün budaması', 'Olgun meyveler dal üzerinde yumuşar'] },
  { product: 'Portakal', productEn: 'Orange', category: 'meyve', plantMonths: [3, 4], harvestMonths: [11, 12, 1, 2, 3], regions: ['Akdeniz'], description: 'Akdeniz ikliminin sembol meyvesi. Washington Navel, Valencia çeşitleri. Adana, Mersin, Hatay yoğunlaşmış.', tips: ['Don koruması için rüzgar perdeleri oluşturun', 'Akdeniz sineğine karşı tuzak asın', 'Ağaç başına yıllık gübre programı uygulayın'] },
  { product: 'Mandalina', productEn: 'Mandarin', category: 'meyve', plantMonths: [3, 4], harvestMonths: [10, 11, 12, 1, 2], regions: ['Akdeniz'], description: 'Satsuma, Clementine, Okitsu çeşitleri. Türkiye AB\'ye en çok ihraç eden ülkelerden.', tips: ['Geç meyve tutumu olursa besin takviyesi şart', 'Kabuk yumuşaması olgunluk göstergesi', 'Hasat öncesi iki hafta sulama azaltın'] },
  { product: 'Limon', productEn: 'Lemon', category: 'meyve', plantMonths: [3, 4], harvestMonths: [9, 10, 11, 12, 1, 2, 3], regions: ['Mersin', 'Hatay', 'Adana'], description: 'Enterdonato, Lamas ve Meyer çeşitleri. Mersin Silifke limonu coğrafi işaretli.', tips: ['Uzun hasat dönemi (6-8 ay)', 'Donla zarar görmemesi için örtü yapın', 'Küf hastalığı için depo havalandırması kritik'] },
  { product: 'Greyfurt', productEn: 'Grapefruit', category: 'meyve', plantMonths: [3, 4], harvestMonths: [11, 12, 1, 2, 3], regions: ['Akdeniz'], description: 'Beyaz, pembe ve kırmızı etli çeşitleri. Adana ve Mersin başlıca üretici.', tips: ['Diğer narenciyelere göre daha sıcak sever', 'Kabuk kalınlığı çeşide göre değişir', 'Tam olgunluk için geç hasat önerilir'] },
  { product: 'İncir', productEn: 'Fig', category: 'meyve', plantMonths: [2, 3], harvestMonths: [7, 8, 9, 10], regions: ['Aydın', 'İzmir', 'Bursa'], description: 'Aydın kuru inciri dünya üretiminin %60\'ı. Sarılop (beyaz) ve siyah incir çeşitleri.', tips: ['İlekleme (doğal tozlaşma) gerekli', 'Hasat günlük yapılır, çabuk bozulur', 'Kurutma için güneşli alan ve serme şart'] },
  { product: 'Nar', productEn: 'Pomegranate', category: 'meyve', plantMonths: [2, 3, 11, 12], harvestMonths: [9, 10, 11], regions: ['Antalya', 'Hatay', 'Akdeniz', 'Ege'], description: 'Hicaznar en popüler çeşit. İhracat potansiyeli yüksek. Antioksidan zengini.', tips: ['Meyve çatlamaması için düzenli sulama şart', 'Nar güvesi için feromon tuzak kullanın', 'Yeşil kabuk pembeleştiğinde hasat edin'] },
  { product: 'Üzüm', productEn: 'Grape', category: 'meyve', plantMonths: [2, 3], harvestMonths: [7, 8, 9, 10], regions: ['Ege', 'Akdeniz', 'İç Anadolu', 'Güneydoğu Anadolu'], description: 'Sofralık (Sultani, Red Globe), kurutmalık (Sultaniye) ve şaraplık çeşitler.', tips: ['Kış budaması Şubat\'ta yapılmalı', 'Külleme ve mildiyö için zamanında ilaçlama', 'Kurutmalık üzüm için serpme yöntemi kullanın'] },
  { product: 'Çilek', productEn: 'Strawberry', category: 'meyve', plantMonths: [8, 9, 10], harvestMonths: [3, 4, 5, 6], regions: ['Mersin', 'Aydın', 'Bursa'], description: 'Aromas, Camarosa, Albion çeşitleri. Mersin Türkiye\'nin üretim merkezi.', tips: ['Her 2-3 yılda fide yenileme şart', 'Kurtlanmaya karşı malç kullanın', 'Kırmızılaşınca sap ile toplayın'] },
  { product: 'Trabzon Hurması', productEn: 'Persimmon', category: 'meyve', plantMonths: [2, 3, 11, 12], harvestMonths: [10, 11, 12], regions: ['Akdeniz', 'Ege', 'Marmara'], description: 'Fuyu ve Hachiya çeşitleri. Don dayanımı iyi, çok az bakım ister.', tips: ['Buruk olmayan çeşitler taze tüketilir', 'Don sonrası tatlılaşır', 'Nakliye için sert hasat edilmeli'] },
  { product: 'Kivi', productEn: 'Kiwi', category: 'meyve', plantMonths: [2, 3], harvestMonths: [10, 11, 12], regions: ['Karadeniz (Yalova, Rize)', 'Marmara'], description: 'Yalova ve Rize\'de yoğunlaşmış. Yüksek C vitamini içeriği.', tips: ['Erkek-dişi oranı 1:8 olmalı (tozlaşma)', 'Meyveler 5-15 derece arası depolama', 'Sert iken hasat, olgunlaştırma sonra'] },
  { product: 'Muz', productEn: 'Banana', category: 'meyve', plantMonths: [3, 4, 5], harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], regions: ['Anamur', 'Alanya', 'Antalya'], description: 'Türkiye\'nin ana muz üretim merkezi Anamur. Yıl boyu hasat alınır.', tips: ['Don koruması için sera veya örtü şart', 'Her ağaçtan bir sezonluk hasat (sonra kesilir)', 'Yeşilken hasat, kontrollü ortamda olgunlaştırma'] },
  { product: 'Avokado', productEn: 'Avocado', category: 'meyve', plantMonths: [3, 4], harvestMonths: [10, 11, 12, 1, 2], regions: ['Akdeniz (Alanya, Anamur)'], description: 'Türkiye\'de 2015 sonrası hızla yaygınlaşan yeni meyve. Hass ve Fuerte çeşitleri.', tips: ['Dona çok hassas, örtü zorunlu', 'Dalında olgunlaşmaz, hasat sonrası yumuşar', '10-15°C depolama ideal'] },
  { product: 'Zeytin', productEn: 'Olive', category: 'meyve', plantMonths: [2, 3, 11, 12], harvestMonths: [10, 11, 12, 1], regions: ['Ege', 'Marmara', 'Akdeniz', 'Güneydoğu Anadolu'], description: 'Türkiye dünyanın 3. zeytin üreticisi. Sofralık (Gemlik) ve yağlık çeşitler.', tips: ['Periyodisiteye karşı yıllık budama', 'Zeytin sineği için feromon tuzak kritik', 'Sofralık yeşil, yağlık siyah hasat edilir'] },
  { product: 'Fındık', productEn: 'Hazelnut', category: 'meyve', plantMonths: [11, 12, 1, 2], harvestMonths: [8, 9], regions: ['Karadeniz'], description: 'Türkiye dünya fındık üretiminin %70\'ini karşılar. Giresun ve Ordu başlıca üretici.', tips: ['Ocak yapısını 4-5 dal ile sınırlayın', 'Külleme ve kokarca böceğine dikkat', 'Hasat zamanlaması çotanak rengine göre yapılır'] },
  { product: 'Ceviz', productEn: 'Walnut', category: 'meyve', plantMonths: [2, 3, 11, 12], harvestMonths: [9, 10], regions: ['İç Anadolu', 'Karadeniz', 'Ege'], description: 'Chandler, Fernor ve yerli çeşitler. Meyvesi + odunu ekonomik değerli.', tips: ['Sert kabukluya yaprak bitkisi anterak için ilaçla', 'Yeşil kabuk çatlayınca hasat başlar', 'Kurutma için serme ve havalandırma şart'] },
  { product: 'Badem', productEn: 'Almond', category: 'meyve', plantMonths: [12, 1, 2], harvestMonths: [8, 9], regions: ['Akdeniz', 'Ege', 'Güneydoğu Anadolu'], description: 'Kurak iklime dayanıklı kuruyemiş ağacı. Nonpareil, Ferragnes çeşitleri.', tips: ['Geç çiçeklenen çeşit seçin (don riski)', 'Yeşil kabuk çatlayınca sarsın', 'Kabuk soyma ve kurutma gerekli'] },
  { product: 'Antep Fıstığı', productEn: 'Pistachio', category: 'meyve', plantMonths: [2, 3, 11, 12], harvestMonths: [8, 9], regions: ['Gaziantep', 'Şanlıurfa', 'Siirt'], description: 'Coğrafi işaretli Türkiye klasiği. 2 yılda bir yüksek verim (periyodisite).', tips: ['Erkek-dişi ağaç oranı 1:10 olmalı', 'Hasat öncesi sulama çatlamaya neden olur', 'Kabuklar açıldığında sarsma ile hasat'] },
  { product: 'Kestane', productEn: 'Chestnut', category: 'meyve', plantMonths: [11, 12, 1, 2], harvestMonths: [9, 10, 11], regions: ['Karadeniz', 'Marmara (Bursa)', 'Ege'], description: 'Bursa kestanesi coğrafi işaretli. Don zararına çok hassas.', tips: ['Kestane gal arısına karşı biyolojik mücadele', 'Olgun meyveler düşer, yerden toplanır', 'Depolama öncesi sıcak su ile dezenfeksiyon'] },
  { product: 'Dut', productEn: 'Mulberry', category: 'meyve', plantMonths: [2, 3, 11, 12], harvestMonths: [6, 7], regions: ['İç Anadolu', 'Güneydoğu Anadolu', 'Ege'], description: 'Ak, kara ve kırmızı dut çeşitleri. Pekmez, pestil ve kurutmalık.', tips: ['Çabuk bozulur, günlük hasat', 'Serme ile pekmez için kurutma', 'Dal sarsma en yaygın hasat yöntemi'] },
  { product: 'Ahududu', productEn: 'Raspberry', category: 'meyve', plantMonths: [2, 3, 10, 11], harvestMonths: [6, 7, 8, 9], regions: ['Karadeniz', 'Marmara'], description: 'Türkiye\'de üretimi hızla artan ekonomik meyve. Kısa raf ömrü.', tips: ['Sürgün budaması verim için kritik', 'Soğuk zincir şart', 'Pazar öncesi hemen hasat'] },
  { product: 'Böğürtlen', productEn: 'Blackberry', category: 'meyve', plantMonths: [2, 3, 10, 11], harvestMonths: [7, 8, 9], regions: ['Karadeniz', 'Marmara', 'Ege'], description: 'Dikenli ve dikensiz çeşitleri. Reçel ve dondurmada kullanılır.', tips: ['Destek sistemi ile dikey yetiştirme', 'Olgun meyveler kolay dökülür', 'Güneş yanığı için yarı gölge tercih'] },
  { product: 'Yabanmersini', productEn: 'Blueberry', category: 'meyve', plantMonths: [2, 3, 10, 11], harvestMonths: [6, 7, 8], regions: ['Karadeniz'], description: 'Asitli toprak isteyen süperfood. Türkiye\'de son yıllarda yaygınlaştı.', tips: ['pH 4.5-5.5 olmalı, toprak asitleştirme gerekir', 'Seçici hasat (her meyve ayrı gün)', 'Soğuk zincir ve modern ambalaj şart'] },
  { product: 'Çay', productEn: 'Tea', category: 'meyve', plantMonths: [3, 4], harvestMonths: [5, 6, 7, 8, 9, 10], regions: ['Karadeniz (Rize)'], description: 'Rize başta olmak üzere Doğu Karadeniz\'de yoğun üretim. Yılda 3-4 hasat.', tips: ['İlk sürgün en kaliteli çaydır', 'Budama Şubat-Mart\'ta yapılır', 'Yamaç arazilerde erozyon önlemi alın'] },

  // ═══════════════════════════════════════════════════════════
  // TAHILLAR
  // ═══════════════════════════════════════════════════════════
  { product: 'Buğday', productEn: 'Wheat', category: 'tahil', plantMonths: [10, 11], harvestMonths: [6, 7], regions: ['İç Anadolu', 'Güneydoğu Anadolu', 'Marmara'], description: 'Türkiye\'nin en önemli tahıl ürünü. Kışlık ve yazlık çeşitleri bulunur.', tips: ['Ekim zamanı toprak nemi kritik', 'Yabancı ot mücadelesini kardeşlenme döneminde yapın', 'Süne zararlısına karşı ilaçlama programı uygulayın'] },
  { product: 'Arpa', productEn: 'Barley', category: 'tahil', plantMonths: [10, 11], harvestMonths: [6, 7], regions: ['İç Anadolu', 'Güneydoğu Anadolu'], description: 'Hayvan yemi ve bira yapımında kullanılır. Buğdaydan daha erken olgunlaşır.', tips: ['Kurak bölgelere uygun çeşit seçin', 'Yaprak hastalıklarına karşı fungisit uygulayın', 'Hasattan 1 hafta önce nem kontrolü yapın'] },
  { product: 'Mısır', productEn: 'Corn', category: 'tahil', plantMonths: [4, 5], harvestMonths: [9, 10], regions: ['Akdeniz', 'Güneydoğu Anadolu', 'Karadeniz'], description: 'İkinci ürün olarak da yetiştirilebilir. Sıcak ve bol su ister.', tips: ['Toprağın 10°C üzerine çıkmasını bekleyin', 'Koçan kurdu için biyolojik mücadele uygulayın', 'Damla sulama su tasarrufu sağlar'] },
  { product: 'Çavdar', productEn: 'Rye', category: 'tahil', plantMonths: [9, 10, 11], harvestMonths: [7, 8], regions: ['İç Anadolu', 'Doğu Anadolu', 'Karadeniz'], description: 'Buğdaya göre daha fakir topraklarda yetişebilen kışlık tahıl. Ekmek ve yem.', tips: ['Yüksek rakımlarda iyi sonuç verir', 'Süne zararlısına buğdaydan daha dayanıklı', 'Yeşil gübre olarak da kullanılır'] },
  { product: 'Yulaf', productEn: 'Oat', category: 'tahil', plantMonths: [3, 4, 10], harvestMonths: [6, 7, 8], regions: ['İç Anadolu', 'Karadeniz', 'Marmara'], description: 'İnsan ve hayvan gıdasında kullanılır. Kahvaltılık gevrek popülerliğinden dolayı artan talep.', tips: ['Hem yazlık hem kışlık ekim mümkün', 'Kurakliğa hassastır, nemli bölgelerde yetiştirin', 'Hasat öncesi yatma önemli sorun'] },
  { product: 'Pirinç (Çeltik)', productEn: 'Rice', category: 'tahil', plantMonths: [4, 5], harvestMonths: [9, 10], regions: ['Edirne', 'Samsun', 'Çorum'], description: 'Baldo ve Osmancık çeşitleri öne çıkar. Su kaynakları yakın ovalarda yetişir.', tips: ['Su tavası sistemi ile üretilir', 'Çeltik böcüğüne karşı ilaçlama programı', 'Hasat öncesi su kesilmeli'] },
  { product: 'Tritikale', productEn: 'Triticale', category: 'tahil', plantMonths: [10, 11], harvestMonths: [6, 7], regions: ['İç Anadolu', 'Marmara', 'Ege'], description: 'Buğday-çavdar melezi hibrit tahıl. Hem tane hem hayvan yemi olarak değerli.', tips: ['Buğdaya benzer ekim', 'Fakir topraklarda buğdaydan iyi verim', 'Silajlık ve kaba yem için alternatif'] },

  // ═══════════════════════════════════════════════════════════
  // BAKLAGILLER
  // ═══════════════════════════════════════════════════════════
  { product: 'Mercimek', productEn: 'Lentil', category: 'baklagil', plantMonths: [10, 11, 3], harvestMonths: [6, 7], regions: ['Güneydoğu Anadolu', 'İç Anadolu'], description: 'Kırmızı ve yeşil mercimek. Türkiye dünya pazarında önemli üretici.', tips: ['Ekim derinliği 4-5 cm olmalı', 'Yabancı ot mücadelesi kritik', 'Hasatta tane dökülmesine dikkat'] },
  { product: 'Nohut', productEn: 'Chickpea', category: 'baklagil', plantMonths: [3, 4], harvestMonths: [7, 8], regions: ['İç Anadolu', 'Güneydoğu Anadolu'], description: 'Türk mutfağının vazgeçilmezi. Kurak koşullara dayanıklı.', tips: ['Antraknoz hastalığına dayanıklı çeşit seçin', 'Ekim nöbeti uygulayın', 'Tane nemi %13\'ün altına düşünce hasat edin'] },
  { product: 'Kuru Fasulye', productEn: 'Dry Bean', category: 'baklagil', plantMonths: [4, 5], harvestMonths: [8, 9, 10], regions: ['İç Anadolu (Nevşehir)', 'Erzincan', 'Karaman'], description: 'İspir kuru fasulyesi ve Nevşehir fasulyesi coğrafi işaretli. Protein kaynağı.', tips: ['Don riski bittikten sonra ekim', 'Destek sistemi sırık çeşitleri için', 'Hasat sonrası iyi kurutma şart'] },
  { product: 'Kuru Bakla', productEn: 'Dry Broad Bean', category: 'baklagil', plantMonths: [10, 11, 2, 3], harvestMonths: [6, 7], regions: ['Akdeniz', 'Ege'], description: 'Kışlık baklagil. Hem insan gıdası hem hayvan yemi (yemlik bakla).', tips: ['Soğuğa dayanıklı, kış başı ekim', 'Yaprak biti ana sorun', 'Tane sertleşince hasat'] },
  { product: 'Börülce', productEn: 'Cowpea', category: 'baklagil', plantMonths: [4, 5, 6], harvestMonths: [7, 8, 9], regions: ['Akdeniz', 'Ege', 'Güneydoğu Anadolu'], description: 'Sıcak iklim baklagili. Kuru ve taze (baklası) tüketilebilir.', tips: ['İkinci ürün olarak buğday sonrası yetişir', 'Kurak koşullara dayanıklı', 'Yeşil gübreleme için de kullanılır'] },

  // ═══════════════════════════════════════════════════════════
  // YAGLI TOHUMLAR (yeni kategori)
  // ═══════════════════════════════════════════════════════════
  { product: 'Ayçiçeği', productEn: 'Sunflower', category: 'yagli-tohum', plantMonths: [3, 4, 5], harvestMonths: [8, 9, 10], regions: ['Trakya', 'İç Anadolu', 'Karadeniz'], description: 'Türkiye\'nin en önemli yağlı tohum bitkisi. Trakya bölgesi üretim merkezi.', tips: ['Hibrit çeşit sertifikalı tohum kullanın', 'Çanak üstü olgunlaştığında hasat', 'Orobanş (canavar otu) için dayanıklı çeşit seçin'] },
  { product: 'Susam', productEn: 'Sesame', category: 'yagli-tohum', plantMonths: [5, 6], harvestMonths: [8, 9], regions: ['Güneydoğu Anadolu', 'Akdeniz', 'Ege'], description: 'Tahin, helva ve simit için ana hammadde. Kurak koşullara dayanıklı.', tips: ['Orta sıcak iklim ister', 'Alt yapraklar sararınca hasat', 'Serme ile doğal kurutma yapılır'] },
  { product: 'Kolza (Kanola)', productEn: 'Canola', category: 'yagli-tohum', plantMonths: [9, 10], harvestMonths: [6, 7], regions: ['Trakya', 'Çukurova', 'Marmara'], description: 'Kışlık yağlı tohum. Biyodizel hammaddesi olarak da değerli.', tips: ['Kışa girmeden 6-8 yaprak olmalı', 'Rapus yaprak biti için ilaçlama', 'Kendiliğinden dökülmeye karşı erken hasat'] },
  { product: 'Haşhaş', productEn: 'Poppy', category: 'yagli-tohum', plantMonths: [9, 10, 3], harvestMonths: [6, 7], regions: ['Afyon', 'Burdur', 'İç Anadolu'], description: 'Türkiye\'de kontrollü lisanslı üretim. Afyon ve Burdur ana merkezler.', tips: ['TMO lisansı zorunludur', 'Kapsül sertleşip sararınca hasat', 'Tohumlar gıda, kapsül ise endüstriyel'] },
  { product: 'Yer Fıstığı', productEn: 'Peanut', category: 'yagli-tohum', plantMonths: [4, 5], harvestMonths: [9, 10], regions: ['Osmaniye', 'Adana', 'Akdeniz'], description: 'Osmaniye coğrafi işaretli. Sıcak iklim ve gevşek kumlu toprak ister.', tips: ['Toprak 18°C üzerinde ekim başlar', 'Aflatoksin için hasat sonrası hızlı kurutma', 'Yaprak sararınca söküm'] },
  { product: 'Soya', productEn: 'Soybean', category: 'yagli-tohum', plantMonths: [5, 6], harvestMonths: [9, 10], regions: ['Akdeniz', 'Güneydoğu Anadolu'], description: 'İkinci ürün olarak yetiştirilir. Hem yağ hem de protein (yem) için.', tips: ['Toprak inokulasyonu (rhizobium) şart', 'Yaprak dökümünden sonra hasat', 'Nem %14 altına düşünce depolayın'] },

  // ═══════════════════════════════════════════════════════════
  // ENDUSTRI BITKILERI (yeni kategori)
  // ═══════════════════════════════════════════════════════════
  { product: 'Pamuk', productEn: 'Cotton', category: 'endustri', plantMonths: [4, 5], harvestMonths: [9, 10, 11], regions: ['Güneydoğu Anadolu', 'Ege', 'Çukurova'], description: 'GAP bölgesi üretimi artırdı. Tekstil sektörünün temel hammaddesi.', tips: ['Pamuk yaprak kurdu için yakın takip', 'Koza açımı %60 iken hasat başlar', 'Makinali hasat nem düzeyine hassas'] },
  { product: 'Şeker Pancarı', productEn: 'Sugar Beet', category: 'endustri', plantMonths: [3, 4], harvestMonths: [9, 10, 11], regions: ['İç Anadolu (Konya, Eskişehir)', 'Doğu Anadolu'], description: 'Şeker üretiminin ana hammaddesi. Türkşeker sözleşmeli üretim yapar.', tips: ['Tekil sulama kritik verim faktörü', 'Yaprak biti ve cercospora için koruyucu ilaçlama', 'Şeker oranı için hasat öncesi sulamayı kesin'] },
  { product: 'Tütün', productEn: 'Tobacco', category: 'endustri', plantMonths: [3, 4, 5], harvestMonths: [7, 8, 9], regions: ['Ege', 'Karadeniz (Samsun)', 'Güneydoğu Anadolu'], description: 'Oryantal (Türk) tütünü dünyaca ünlü. Sözleşmeli üretim yapılır.', tips: ['Alt yapraklardan başlayarak kademeli hasat', 'Kurutma istasyonunda renk kontrolü', 'Yaprak başına dip yapma ile iri yaprak'] },

  // ═══════════════════════════════════════════════════════════
  // YEM BITKILERI
  // ═══════════════════════════════════════════════════════════
  { product: 'Yonca', productEn: 'Alfalfa', category: 'yem-bitkileri', plantMonths: [3, 4, 9], harvestMonths: [5, 6, 7, 8, 9, 10], regions: ['İç Anadolu', 'Doğu Anadolu', 'Ege'], description: 'En kaliteli kaba yem bitkisi. Yılda 4-6 biçim alınabilir. Protein değeri yüksek.', tips: ['İlk biçimde %10 çiçeklenme dönemini bekleyin', 'Her biçimden sonra sulama yapın', 'Kış öncesi son biçimi Ekim ortasına kadar yapın'] },
  { product: 'Silajlık Mısır', productEn: 'Silage Corn', category: 'yem-bitkileri', plantMonths: [4, 5], harvestMonths: [8, 9], regions: ['Akdeniz', 'Marmara', 'Karadeniz'], description: 'Büyükbaş hayvan beslemede temel yem kaynağı. Yüksek enerji değeri.', tips: ['Silaj yapımında kuru madde oranı %30-35 olmalı', 'Silo kapatma hızlı yapılmalı', 'Hamur olum döneminde hasat edin'] },
  { product: 'Fiğ', productEn: 'Vetch', category: 'yem-bitkileri', plantMonths: [9, 10, 3], harvestMonths: [5, 6, 7], regions: ['İç Anadolu', 'Doğu Anadolu', 'Marmara'], description: 'Adi fiğ, macar fiği ve tüylü fiğ çeşitleri. Yeşil gübre olarak da kullanılır.', tips: ['Baklagil olarak azot bağlar', 'Tahıl ile karışık ekilir (ot + tahil)', 'Çiçeklenme başında biçim yapın'] },
  { product: 'Korunga', productEn: 'Sainfoin', category: 'yem-bitkileri', plantMonths: [3, 4, 9], harvestMonths: [5, 6, 7], regions: ['İç Anadolu', 'Doğu Anadolu'], description: 'Kıraç ve çorak topraklara uyum sağlayan yem bitkisi. Arı otu olarak da değerli.', tips: ['Yoncaya alternatif kurağa dayanıklı', 'Arılar için önemli bir nektar kaynağı', '3-4 yıl verimli kalır'] },
  { product: 'Üçgül', productEn: 'Clover', category: 'yem-bitkileri', plantMonths: [3, 4, 9, 10], harvestMonths: [5, 6, 7, 8], regions: ['Karadeniz', 'Marmara', 'Ege'], description: 'Ak ve kırmızı çeşitleri. Mera karışımlarında sıkça kullanılır.', tips: ['Nemli bölgeler daha verimli', 'Otlatma ile sık tekrar büyüme', 'Azot ihtiyacını kendi karşılar'] },

  // ═══════════════════════════════════════════════════════════
  // HAYVANCILIK
  // ═══════════════════════════════════════════════════════════
  { product: 'Süt Sığırcılığı', productEn: 'Dairy Cattle', category: 'hayvancilik', plantMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], regions: ['Tüm bölgeler'], description: 'Holstein, Simental ve Jersey ırkları. Günlük ortalama 20-30 L süt verimi.', tips: ['Kaliteli kaba yem (yonca, silaj) esastır', 'Günde 2-3 kez sağım', 'Buzağılama aralığı 12-13 ay optimal'] },
  { product: 'Besi Sığırcılığı', productEn: 'Beef Cattle', category: 'hayvancilik', plantMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], regions: ['Tüm bölgeler'], description: 'Et üretimine yönelik büyükbaş. 12-18 ayda kesim ağırlığına ulaşır.', tips: ['Kaba yem + konsantre yem dengesi kritik', 'Günlük canlı ağırlık artışı 1-1.2 kg hedef', 'Hastalık önlemi aşı takvimine uyun'] },
  { product: 'Küçükbaş (Koyun)', productEn: 'Sheep', category: 'hayvancilik', plantMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], regions: ['Doğu Anadolu', 'İç Anadolu', 'Güneydoğu Anadolu'], description: 'Akkaraman, Morkaraman, Kıvırcık ve İvesi ırkları. Hem et hem süt hem yün.', tips: ['Kuzulama dönemi Şubat-Mart yoğun', 'Mera + kaba yem yeterli', 'Yıllık kırkım Mayıs-Haziran\'da'] },
  { product: 'Küçükbaş (Keçi)', productEn: 'Goat', category: 'hayvancilik', plantMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], regions: ['Akdeniz', 'Ege', 'Doğu Anadolu'], description: 'Kıl keçisi ve Saanen en yaygın. Süt ve et amaçlı yetiştirilir.', tips: ['Engebeli alanlarda daha verimli', 'Keçi sütü artan talep görmekte', 'Yüksek yaprak ihtiyacı (ağaç otlaması)'] },
  { product: 'Arıcılık (Bal)', productEn: 'Beekeeping', category: 'hayvancilik', plantMonths: [3, 4, 5], harvestMonths: [6, 7, 8, 9], regions: ['Tüm bölgeler (özellikle Muğla, Ordu)'], description: 'Muğla Çam Balı ve Anzer Balı coğrafi işaretli. Türkiye dünya üretiminde lider.', tips: ['Mevsimsel göç (transhümans) verimi artırır', 'Varroa akarına karşı düzenli müdahale', 'Kış öncesi yeterli bal bırakın (15-20 kg)'] },
  { product: 'Kümes Hayvanları', productEn: 'Poultry', category: 'hayvancilik', plantMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], regions: ['Tüm bölgeler'], description: 'Broiler (et), yumurtacı tavuk, hindi, ördek. Entegre üretim sistemi yaygın.', tips: ['Biyogüvenlik kuralları kritik', 'Broiler 40-45 gün kesim', 'Yumurta için günde 16 saat ışık'] },
  { product: 'Su Ürünleri (Alabalık)', productEn: 'Trout', category: 'hayvancilik', plantMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], regions: ['Karadeniz', 'Ege', 'Akdeniz'], description: 'Gökkuşağı alabalığı + levrek, çipura. Türkiye AB\'nin önemli ihracatçısı.', tips: ['Su kalitesi (oksijen, sıcaklık) sürekli izlenir', 'Yem dönüşüm oranı 1.1-1.3 hedef', 'Hasat ağırlığı 300-400 g ideal'] },
];

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/hasatlink');
    console.log('MongoDB connected for feature seeding');

    // 1) Feature flag'ları aç
    const features = [
      'qnaForum', 'harvestCalendar', 'logisticsDirectory',
      'weatherAlerts', 'mapView', 'successStories', 'priceForecast',
    ];
    const update: any = {};
    for (const f of features) update[`${f}.enabled`] = true;

    await SiteSettings.findOneAndUpdate({}, { $set: update }, { upsert: true });
    console.log(`✓ ${features.length} feature flag aktif edildi`);

    // 2) Hasat Takvimi
    await HarvestCalendar.deleteMany({});
    await HarvestCalendar.insertMany(harvestItems);
    console.log(`✓ ${harvestItems.length} hasat takvimi ürünü eklendi`);

    console.log('\n═══════════════════════════════════════');
    console.log('  FEATURE SEED TAMAMLANDI!');
    console.log('  - Forum: AKTİF');
    console.log('  - Hasat Takvimi: AKTİF + veri yüklendi');
    console.log('  - Nakliyeci: Sadece kullanıcı ilanları');
    console.log('  - Hava Uyarıları, Harita, Başarı Hikayeleri: AKTİF');
    console.log('═══════════════════════════════════════\n');

    await mongoose.disconnect();
  } catch (error) {
    console.error('Feature seed error:', error);
    process.exit(1);
  }
};

seed();
